### ISSUE TITLE
Add swift.org to list

### ISSUE THREAD

**Issue by chmaynard** [programmingwithswift/Swift-programming-Tutorials-and-Resources#1]
Just curious, why isn't swift.org included in this list? Seems like all Swift developers would want to be aware of this site.

**Comment by programmingwithswift** [comment]
Thanks for this. Completely forgot about that. Added it into the blog section for now.

**Comment by chmaynard** [comment]
Excellent, thanks. I'd suggest using the blog URL: https://swift.org/blog/

**Comment by programmingwithswift** [comment]
Thanks. Updated. I added in the language guide and reference too.
